[2024-06-09 14:02:42,499: INFO: Welcome to custom log]
[2024-06-09 15:16:26,280: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 15:16:26,284: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:16:26,284: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 15:16:26,286: ERROR: yaml file is empty]
Traceback (most recent call last):
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 259, in __init__
    raise BoxValueError("First argument must be mapping or iterable")
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Anoop Maurya\Documents\GitHub\Kidney-Disease-classification-using-mlflow-and-DVC\main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\config\configuration.py", line 19, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-06-09 15:16:48,679: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 15:16:48,684: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:16:48,697: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 15:16:48,701: ERROR: yaml file is empty]
Traceback (most recent call last):
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 247, in __init__
    raise BoxValueError("Cannot extrapolate Box from string")
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Anoop Maurya\Documents\GitHub\Kidney-Disease-classification-using-mlflow-and-DVC\main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\config\configuration.py", line 19, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-06-09 15:18:18,473: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 15:18:18,476: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:18:18,482: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 15:18:18,483: INFO: created directory at: artifacts]
[2024-06-09 15:18:18,484: INFO: created directory at: artifacts/data_ingestion]
[2024-06-09 15:18:18,486: INFO: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 15:19:57,680: INFO: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 15:19:58,939: INFO: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-09 15:47:24,533: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 15:47:27,036: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 15:47:27,044: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:47:27,045: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 15:47:27,046: INFO: created directory at: artifacts]
[2024-06-09 15:47:27,046: INFO: created directory at: artifacts/data_ingestion]
[2024-06-09 15:47:27,046: INFO: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 15:47:41,954: INFO: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 15:47:43,174: INFO: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-09 15:47:43,175: INFO: *******************]
[2024-06-09 15:47:43,176: INFO: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-09 15:47:43,180: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:47:43,184: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 15:47:43,185: INFO: created directory at: artifacts]
[2024-06-09 15:47:43,186: ERROR: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "c:\Users\Anoop Maurya\Documents\GitHub\Kidney-Disease-classification-using-mlflow-and-DVC\main.py", line 22, in <module>
    prepare_base_model.main()
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2024-06-09 15:48:49,758: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 15:48:50,888: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 15:48:50,891: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:48:50,895: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 15:48:50,895: INFO: created directory at: artifacts]
[2024-06-09 15:48:50,896: INFO: created directory at: artifacts/data_ingestion]
[2024-06-09 15:48:50,897: INFO: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 15:49:06,963: INFO: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 15:49:07,951: INFO: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-09 15:49:07,952: INFO: *******************]
[2024-06-09 15:49:07,952: INFO: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-09 15:49:07,956: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:49:07,959: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 15:49:07,960: INFO: created directory at: artifacts]
[2024-06-09 15:49:07,961: INFO: created directory at: artifacts/prepare_base_model]
[2024-06-09 15:49:27,651: WARNING: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-09 15:49:28,209: INFO: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-09 17:42:55,974: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 17:43:53,426: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 17:43:54,522: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 17:43:54,528: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 17:43:54,533: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 17:43:54,534: INFO: created directory at: artifacts]
[2024-06-09 17:43:54,535: INFO: created directory at: artifacts/data_ingestion]
[2024-06-09 17:43:54,536: INFO: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 17:45:16,278: INFO: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 17:45:17,210: INFO: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-09 17:45:17,218: INFO: *******************]
[2024-06-09 17:45:17,220: INFO: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-09 17:45:17,225: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 17:45:17,228: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 17:45:17,230: INFO: created directory at: artifacts]
[2024-06-09 17:45:17,231: INFO: created directory at: artifacts/prepare_base_model]
[2024-06-09 17:45:17,982: WARNING: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-09 17:45:18,548: INFO: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-09 17:45:18,549: INFO: *******************]
[2024-06-09 17:45:18,549: INFO: >>>>>> stage Training started <<<<<<]
[2024-06-09 17:45:18,552: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 17:45:18,553: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 17:45:18,554: INFO: created directory at: artifacts]
[2024-06-09 17:45:18,555: ERROR: "'ConfigBox' object has no attribute 'training'"]
Traceback (most recent call last):
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'training'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'training'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'training'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'training'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'training'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'training'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'training'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Anoop Maurya\Documents\GitHub\Kidney-Disease-classification-using-mlflow-and-DVC\main.py", line 34, in <module>
    model_trainer.main()
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training_config = config.get_training_config()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\config\configuration.py", line 58, in get_training_config
    training = self.config.training
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'training'"
[2024-06-09 17:47:10,841: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 17:47:11,831: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 17:47:11,860: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 17:47:11,864: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 17:47:11,865: INFO: created directory at: artifacts]
[2024-06-09 17:47:11,868: INFO: created directory at: artifacts/data_ingestion]
[2024-06-09 17:47:11,870: INFO: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 17:47:25,335: INFO: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 17:47:26,356: INFO: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-09 17:47:26,357: INFO: *******************]
[2024-06-09 17:47:26,357: INFO: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-09 17:47:26,365: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 17:47:26,378: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 17:47:26,385: INFO: created directory at: artifacts]
[2024-06-09 17:47:26,389: INFO: created directory at: artifacts/prepare_base_model]
[2024-06-09 17:47:27,107: WARNING: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-09 17:47:27,442: INFO: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-09 17:47:27,442: INFO: *******************]
[2024-06-09 17:47:27,444: INFO: >>>>>> stage Training started <<<<<<]
[2024-06-09 17:47:27,448: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 17:47:27,455: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 17:47:27,458: INFO: created directory at: artifacts]
[2024-06-09 17:47:27,460: INFO: created directory at: artifacts\training]
[2024-06-09 17:50:37,871: INFO: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-06-09 18:46:36,431: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 18:49:25,397: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 18:49:29,958: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 18:49:29,961: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 18:49:29,963: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 18:49:29,965: INFO: created directory at: artifacts]
[2024-06-09 18:49:29,966: INFO: created directory at: artifacts/data_ingestion]
[2024-06-09 18:49:29,967: INFO: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 18:49:58,774: INFO: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 18:49:59,752: INFO: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-09 18:49:59,753: INFO: *******************]
[2024-06-09 18:49:59,754: INFO: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-09 18:49:59,759: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 18:49:59,762: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 18:49:59,762: INFO: created directory at: artifacts]
[2024-06-09 18:49:59,763: INFO: created directory at: artifacts/prepare_base_model]
[2024-06-09 18:50:00,534: WARNING: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-09 18:50:01,072: INFO: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-09 18:50:01,073: INFO: *******************]
[2024-06-09 18:50:01,074: INFO: >>>>>> stage Training started <<<<<<]
[2024-06-09 18:50:01,077: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 18:50:01,079: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 18:50:01,079: INFO: created directory at: artifacts]
[2024-06-09 18:50:01,081: INFO: created directory at: artifacts\training]
[2024-06-09 18:52:33,149: INFO: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-06-09 18:52:33,150: INFO: *******************]
[2024-06-09 18:52:33,151: INFO: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-09 18:52:33,156: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 18:52:33,160: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 18:52:33,163: INFO: created directory at: artifacts]
[2024-06-09 18:53:21,331: INFO: json file saved at: scores.json]
[2024-06-09 18:53:21,334: INFO: json file saved at: scores.json]
[2024-06-09 18:53:21,335: INFO: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-06-09 18:59:41,227: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 18:59:47,347: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 18:59:47,352: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 18:59:47,358: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 18:59:47,359: INFO: created directory at: artifacts]
[2024-06-09 18:59:47,359: INFO: created directory at: artifacts/data_ingestion]
[2024-06-09 18:59:47,360: INFO: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 18:59:59,683: INFO: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 19:00:01,106: INFO: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-09 19:00:01,114: INFO: *******************]
[2024-06-09 19:00:01,127: INFO: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-09 19:00:01,149: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:00:01,175: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 19:00:01,181: INFO: created directory at: artifacts]
[2024-06-09 19:00:01,184: INFO: created directory at: artifacts/prepare_base_model]
[2024-06-09 19:00:03,889: WARNING: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-09 19:00:06,095: INFO: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-09 19:00:06,096: INFO: *******************]
[2024-06-09 19:00:06,097: INFO: >>>>>> stage Training started <<<<<<]
[2024-06-09 19:00:06,103: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:00:06,109: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 19:00:06,110: INFO: created directory at: artifacts]
[2024-06-09 19:00:06,111: INFO: created directory at: artifacts\training]
[2024-06-09 19:01:53,540: ERROR: Graph execution error:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\Normal\\Normal- (795).jpg'
Traceback (most recent call last):

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\ops\script_ops.py", line 267, in __call__
    ret = func(*args)
          ^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\data\ops\from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\engine\data_adapter.py", line 902, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\engine\data_adapter.py", line 1049, in generator_fn
    yield x[i]
          ~^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(
          ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\Normal\\Normal- (795).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "c:\Users\Anoop Maurya\Documents\GitHub\Kidney-Disease-classification-using-mlflow-and-DVC\main.py", line 35, in <module>
    model_trainer.main()
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "c:\users\anoop maurya\documents\github\kidney-disease-classification-using-mlflow-and-dvc\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\execute.py", line 58, in quick_execute
    except TypeError as e:
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\Normal\\Normal- (795).jpg'
Traceback (most recent call last):

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\ops\script_ops.py", line 267, in __call__
    ret = func(*args)
          ^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\data\ops\from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\engine\data_adapter.py", line 902, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\engine\data_adapter.py", line 1049, in generator_fn
    yield x[i]
          ~^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(
          ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Anoop Maurya\AppData\Roaming\Python\Python311\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\Normal\\Normal- (795).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1463]
[2024-06-09 19:11:47,622: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 19:11:54,108: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 19:11:54,131: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:11:54,136: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 19:11:54,138: INFO: created directory at: artifacts]
[2024-06-09 19:11:54,139: INFO: created directory at: artifacts/data_ingestion]
[2024-06-09 19:11:54,145: INFO: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 19:12:11,728: INFO: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-09 19:12:14,159: INFO: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-09 19:12:14,160: INFO: *******************]
[2024-06-09 19:12:14,160: INFO: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-09 19:12:14,167: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:12:14,172: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 19:12:14,173: INFO: created directory at: artifacts]
[2024-06-09 19:12:14,175: INFO: created directory at: artifacts/prepare_base_model]
[2024-06-09 19:12:16,561: WARNING: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-09 19:12:20,011: INFO: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-09 19:12:20,013: INFO: *******************]
[2024-06-09 19:12:20,013: INFO: >>>>>> stage Training started <<<<<<]
[2024-06-09 19:12:20,016: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:12:20,022: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 19:12:20,023: INFO: created directory at: artifacts]
[2024-06-09 19:12:20,024: INFO: created directory at: artifacts\training]
[2024-06-09 19:15:16,719: INFO: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-06-09 19:15:16,720: INFO: *******************]
[2024-06-09 19:15:16,721: INFO: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-09 19:15:16,726: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:15:16,730: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 19:15:16,731: INFO: created directory at: artifacts]
[2024-06-09 19:16:05,595: INFO: json file saved at: scores.json]
[2024-06-09 19:16:05,598: INFO: json file saved at: scores.json]
[2024-06-09 19:16:05,599: INFO: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-06-09 19:17:21,268: INFO: NumExpr defaulting to 4 threads.]
[2024-06-09 19:17:24,182: INFO: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 19:17:24,184: INFO: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:17:24,186: INFO: yaml file: params.yaml loaded successfully]
[2024-06-09 19:17:24,186: INFO: created directory at: artifacts]
[2024-06-09 19:17:24,187: INFO: created directory at: artifacts/data_ingestion]
[2024-06-09 19:17:24,187: INFO: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
